
package com.ysmjjsy.goya.cxfdemo.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-05-08T01:12:06.417+08:00
 * Generated source version: 3.5.2
 */

@WebFault(name = "InvalidMessageContentExpressionFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class InvalidMessageContentExpressionFault extends Exception {

    private com.wisdom.area.webservice.wsdl.InvalidMessageContentExpressionFaultType faultInfo;

    public InvalidMessageContentExpressionFault() {
        super();
    }

    public InvalidMessageContentExpressionFault(String message) {
        super(message);
    }

    public InvalidMessageContentExpressionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidMessageContentExpressionFault(String message, com.wisdom.area.webservice.wsdl.InvalidMessageContentExpressionFaultType invalidMessageContentExpressionFault) {
        super(message);
        this.faultInfo = invalidMessageContentExpressionFault;
    }

    public InvalidMessageContentExpressionFault(String message, com.wisdom.area.webservice.wsdl.InvalidMessageContentExpressionFaultType invalidMessageContentExpressionFault, Throwable cause) {
        super(message, cause);
        this.faultInfo = invalidMessageContentExpressionFault;
    }

    public com.wisdom.area.webservice.wsdl.InvalidMessageContentExpressionFaultType getFaultInfo() {
        return this.faultInfo;
    }
}
