
package com.ysmjjsy.goya.cxfdemo.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-05-08T01:12:06.423+08:00
 * Generated source version: 3.5.2
 */

@WebFault(name = "NotifyMessageNotSupportedFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class NotifyMessageNotSupportedFault extends Exception {

    private com.wisdom.area.webservice.wsdl.NotifyMessageNotSupportedFaultType faultInfo;

    public NotifyMessageNotSupportedFault() {
        super();
    }

    public NotifyMessageNotSupportedFault(String message) {
        super(message);
    }

    public NotifyMessageNotSupportedFault(String message, Throwable cause) {
        super(message, cause);
    }

    public NotifyMessageNotSupportedFault(String message, com.wisdom.area.webservice.wsdl.NotifyMessageNotSupportedFaultType notifyMessageNotSupportedFault) {
        super(message);
        this.faultInfo = notifyMessageNotSupportedFault;
    }

    public NotifyMessageNotSupportedFault(String message, com.wisdom.area.webservice.wsdl.NotifyMessageNotSupportedFaultType notifyMessageNotSupportedFault, Throwable cause) {
        super(message, cause);
        this.faultInfo = notifyMessageNotSupportedFault;
    }

    public com.wisdom.area.webservice.wsdl.NotifyMessageNotSupportedFaultType getFaultInfo() {
        return this.faultInfo;
    }
}
