
package com.ysmjjsy.goya.cxfdemo.webservice;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-05-08T01:12:06.467+08:00
 * Generated source version: 3.5.2
 *
 */

public class NotificationProducer_NotificationProducerPort_Server{

    protected NotificationProducer_NotificationProducerPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new NotificationProducerPortImpl();
        String address = "{rhinHost}/OrganizationProviderNotificationProducer";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new NotificationProducer_NotificationProducerPort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
