
package com.ysmjjsy.goya.cxfdemo.webservice;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-05-08T01:12:06.468+08:00
 * Generated source version: 3.5.2
 *
 */

public class NotificationConsumer_NotificationConsumerPort_Server{

    protected NotificationConsumer_NotificationConsumerPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new NotificationConsumerPortImpl();
        String address = "{OrganizationMessgeApp}/NotificationConsumer";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new NotificationConsumer_NotificationConsumerPort_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
