package com.ysmjjsy.goya.cxfdemo.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-05-08T01:12:06.485+08:00
 * Generated source version: 3.5.2
 *
 */
@WebServiceClient(name = "OrganizationMessageApp",
                  wsdlLocation = "file:/Users/chenjie/IdeaProjects/cxfDemo/src/main/resources/rhin_OrganizationRegistration.wsdl",
                  targetNamespace = "http://www.chiss.org.cn/rhin/2015")
public class OrganizationMessageApp extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.chiss.org.cn/rhin/2015", "OrganizationMessageApp");
    public final static QName NotificationConsumerPort = new QName("http://www.chiss.org.cn/rhin/2015", "NotificationConsumerPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/chenjie/IdeaProjects/cxfDemo/src/main/resources/rhin_OrganizationRegistration.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrganizationMessageApp.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/chenjie/IdeaProjects/cxfDemo/src/main/resources/rhin_OrganizationRegistration.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrganizationMessageApp(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrganizationMessageApp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrganizationMessageApp() {
        super(WSDL_LOCATION, SERVICE);
    }

    public OrganizationMessageApp(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OrganizationMessageApp(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OrganizationMessageApp(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns NotificationConsumer
     */
    @WebEndpoint(name = "NotificationConsumerPort")
    public NotificationConsumer getNotificationConsumerPort() {
        return super.getPort(NotificationConsumerPort, NotificationConsumer.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotificationConsumer
     */
    @WebEndpoint(name = "NotificationConsumerPort")
    public NotificationConsumer getNotificationConsumerPort(WebServiceFeature... features) {
        return super.getPort(NotificationConsumerPort, NotificationConsumer.class, features);
    }

}
