package com.ysmjjsy.goya.cxfdemo.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-05-08T01:12:06.457+08:00
 * Generated source version: 3.5.2
 *
 */
@WebService(targetNamespace = "http://www.chiss.org.cn/rhin/2015", name = "OrganizationProvider")
@XmlSeeAlso({ObjectFactory.class})
public interface OrganizationProvider {

    @WebMethod(operationName = "OrganizationFeed", action = "OrganizationFeed")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "OrganizationFeedResponse", targetNamespace = "http://www.chiss.org.cn/rhin/2015", partName = "message")
    public OrganizationFeedResponse organizationFeed(

        @WebParam(partName = "message", name = "OrganizationFeed", targetNamespace = "http://www.chiss.org.cn/rhin/2015")
        OrganizationFeed message
    );

    @WebMethod(operationName = "OrganizationQuery", action = "OrganizationQuery")
    @RequestWrapper(localName = "OrganizationQuery", targetNamespace = "http://www.chiss.org.cn/rhin/2015", className = "com.wisdom.area.webservice.wsdl.OrganizationQueryRequest")
    @ResponseWrapper(localName = "OrganizationQueryResponse", targetNamespace = "http://www.chiss.org.cn/rhin/2015", className = "com.wisdom.area.webservice.wsdl.OrganizationQueryResponseMessage")
    public void organizationQuery(

        @WebParam(mode = WebParam.Mode.INOUT, name = "from", targetNamespace = "http://www.chiss.org.cn/rhin/2015")
        javax.xml.ws.Holder<java.lang.Integer> from,
        @WebParam(name = "maxCount", targetNamespace = "http://www.chiss.org.cn/rhin/2015")
        com.wisdom.area.webservice.wsdl.Integer maxCount,
        @WebParam(name = "adhocQuery", targetNamespace = "http://www.chiss.org.cn/rhin/2015")
        com.wisdom.area.webservice.wsdl.AdhocQuery adhocQuery,
        @WebParam(mode = WebParam.Mode.OUT, name = "totalCount", targetNamespace = "http://www.chiss.org.cn/rhin/2015")
        javax.xml.ws.Holder<java.lang.Integer> totalCount,
        @WebParam(mode = WebParam.Mode.OUT, name = "count", targetNamespace = "http://www.chiss.org.cn/rhin/2015")
        javax.xml.ws.Holder<java.lang.Integer> count,
        @WebParam(mode = WebParam.Mode.OUT, name = "organization", targetNamespace = "http://www.chiss.org.cn/rhin/2015")
        javax.xml.ws.Holder<java.util.List<com.wisdom.area.webservice.wsdl.Organization>> organization
    );
}
