
package com.ysmjjsy.goya.cxfdemo.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-05-08T01:12:06.437+08:00
 * Generated source version: 3.5.2
 */

@WebFault(name = "SubscribeCreationFailedFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class SubscribeCreationFailedFault extends Exception {

    private com.wisdom.area.webservice.wsdl.SubscribeCreationFailedFaultType faultInfo;

    public SubscribeCreationFailedFault() {
        super();
    }

    public SubscribeCreationFailedFault(java.lang.String message) {
        super(message);
    }

    public SubscribeCreationFailedFault(java.lang.String message, Throwable cause) {
        super(message, cause);
    }

    public SubscribeCreationFailedFault(java.lang.String message, com.wisdom.area.webservice.wsdl.SubscribeCreationFailedFaultType subscribeCreationFailedFault) {
        super(message);
        this.faultInfo = subscribeCreationFailedFault;
    }

    public SubscribeCreationFailedFault(java.lang.String message, com.wisdom.area.webservice.wsdl.SubscribeCreationFailedFaultType subscribeCreationFailedFault, Throwable cause) {
        super(message, cause);
        this.faultInfo = subscribeCreationFailedFault;
    }

    public com.wisdom.area.webservice.wsdl.SubscribeCreationFailedFaultType getFaultInfo() {
        return this.faultInfo;
    }
}
