
package com.ysmjjsy.goya.cxfdemo.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-05-08T01:12:06.414+08:00
 * Generated source version: 3.5.2
 */

@WebFault(name = "TopicNotSupportedFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class TopicNotSupportedFault extends Exception {

    private com.wisdom.area.webservice.wsdl.TopicNotSupportedFaultType faultInfo;

    public TopicNotSupportedFault() {
        super();
    }

    public TopicNotSupportedFault(java.lang.String message) {
        super(message);
    }

    public TopicNotSupportedFault(java.lang.String message, Throwable cause) {
        super(message, cause);
    }

    public TopicNotSupportedFault(java.lang.String message, com.wisdom.area.webservice.wsdl.TopicNotSupportedFaultType topicNotSupportedFault) {
        super(message);
        this.faultInfo = topicNotSupportedFault;
    }

    public TopicNotSupportedFault(java.lang.String message, com.wisdom.area.webservice.wsdl.TopicNotSupportedFaultType topicNotSupportedFault, Throwable cause) {
        super(message, cause);
        this.faultInfo = topicNotSupportedFault;
    }

    public com.wisdom.area.webservice.wsdl.TopicNotSupportedFaultType getFaultInfo() {
        return this.faultInfo;
    }
}
