
package com.ysmjjsy.goya.cxfdemo.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-05-08T01:12:06.385+08:00
 * Generated source version: 3.5.2
 */

@WebFault(name = "UnacceptableTerminationTimeFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class UnacceptableTerminationTimeFault extends Exception {

    private com.wisdom.area.webservice.wsdl.UnacceptableTerminationTimeFaultType faultInfo;

    public UnacceptableTerminationTimeFault() {
        super();
    }

    public UnacceptableTerminationTimeFault(java.lang.String message) {
        super(message);
    }

    public UnacceptableTerminationTimeFault(java.lang.String message, Throwable cause) {
        super(message, cause);
    }

    public UnacceptableTerminationTimeFault(java.lang.String message, com.wisdom.area.webservice.wsdl.UnacceptableTerminationTimeFaultType unacceptableTerminationTimeFault) {
        super(message);
        this.faultInfo = unacceptableTerminationTimeFault;
    }

    public UnacceptableTerminationTimeFault(java.lang.String message, com.wisdom.area.webservice.wsdl.UnacceptableTerminationTimeFaultType unacceptableTerminationTimeFault, Throwable cause) {
        super(message, cause);
        this.faultInfo = unacceptableTerminationTimeFault;
    }

    public com.wisdom.area.webservice.wsdl.UnacceptableTerminationTimeFaultType getFaultInfo() {
        return this.faultInfo;
    }
}
