
package com.ysmjjsy.goya.cxfdemo.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.5.2
 * 2022-05-08T01:12:06.436+08:00
 * Generated source version: 3.5.2
 */

@WebFault(name = "UnsupportedPolicyRequestFault", targetNamespace = "http://docs.oasis-open.org/wsn/b-2")
public class UnsupportedPolicyRequestFault extends Exception {

    private com.wisdom.area.webservice.wsdl.UnsupportedPolicyRequestFaultType faultInfo;

    public UnsupportedPolicyRequestFault() {
        super();
    }

    public UnsupportedPolicyRequestFault(java.lang.String message) {
        super(message);
    }

    public UnsupportedPolicyRequestFault(java.lang.String message, Throwable cause) {
        super(message, cause);
    }

    public UnsupportedPolicyRequestFault(java.lang.String message, com.wisdom.area.webservice.wsdl.UnsupportedPolicyRequestFaultType unsupportedPolicyRequestFault) {
        super(message);
        this.faultInfo = unsupportedPolicyRequestFault;
    }

    public UnsupportedPolicyRequestFault(java.lang.String message, com.wisdom.area.webservice.wsdl.UnsupportedPolicyRequestFaultType unsupportedPolicyRequestFault, Throwable cause) {
        super(message, cause);
        this.faultInfo = unsupportedPolicyRequestFault;
    }

    public com.wisdom.area.webservice.wsdl.UnsupportedPolicyRequestFaultType getFaultInfo() {
        return this.faultInfo;
    }
}
